# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Install build dependencies
RUN apt-get update && apt-get install -y --no-install-recommends gcc build-essential && rm -rf /var/lib/apt/lists/*

# Copy project files
COPY pyproject.toml ./
COPY setup.py ./
COPY README.md ./
COPY src ./src
COPY tests ./tests
COPY scripts ./scripts
COPY LICENSE ./

# Install hatchling first to satisfy build requirements
RUN pip install hatchling

# Install the package without running prepare scripts
RUN pip install . --no-build-isolation --upgrade

# Define entrypoint
ENTRYPOINT ["mcp-openvision"]
